// registry/neo-brutalism/card/Card.tsx
// Neo-Brutalism — Card (React skin, Layer 3). Optional header/footer regions are
// separated from the body by a hard rule (in the CSS). See DESIGN.md, Entries 31–33.
import type { HTMLAttributes, ReactNode } from 'react';
import './tokens.css';
import './card.css';

export type CardVariant = 'paper' | 'primary' | 'secondary' | 'muted';
export type CardFooterAlign = 'end' | 'center' | 'start' | 'between';

type Props = {
	variant?: CardVariant;
	header?: ReactNode;
	footer?: ReactNode;
	/** How footer actions are arranged along the row. */
	footerAlign?: CardFooterAlign;
	children?: ReactNode;
} & HTMLAttributes<HTMLDivElement>;

export function Card({
	variant = 'paper',
	header,
	footer,
	footerAlign = 'end',
	children,
	...rest
}: Props) {
	return (
		<div className="nb-card" data-variant={variant} {...rest}>
			{header ? <div className="nb-card__header">{header}</div> : null}
			{children ? <div className="nb-card__body">{children}</div> : null}
			{footer ? (
				<div className="nb-card__footer" data-footer-align={footerAlign}>
					{footer}
				</div>
			) : null}
		</div>
	);
}

export default Card;

// src/lib/neo-brutalism/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';
	import type { CardVariant, CardFooterAlign } from './options.js';
	import '../styles/neo-brutalism.css';
	import './css/card.css';

	type Props = {
		variant?: CardVariant;
		/** Optional header region, separated from the body by a hard rule. */
		header?: Snippet;
		/** Optional footer region, separated from the body by a hard rule. */
		footer?: Snippet;
		/** How footer actions are arranged along the row. */
		footerAlign?: CardFooterAlign;
		children?: Snippet;
	} & HTMLAttributes<HTMLDivElement>;

	let {
		variant = 'paper',
		header,
		footer,
		footerAlign = 'end',
		children,
		...rest
	}: Props = $props();
</script>

<div class="nb-card" data-variant={variant} {...rest}>
	{#if header}<div class="nb-card__header">{@render header()}</div>{/if}
	{#if children}<div class="nb-card__body">{@render children()}</div>{/if}
	{#if footer}<div class="nb-card__footer" data-footer-align={footerAlign}>{@render footer()}</div>{/if}
</div>
