// registry/glassmorphism/toggle/Toggle.tsx
// Glassmorphism — Toggle (React skin, Layer 3). A real <button role="switch"> with
// aria-checked. The track/thumb are driven by `data-checked` (JS state), so it's
// controlled-with-uncontrolled-fallback: pass `checked` + `onCheckedChange` to
// control it, or leave it and it tracks its own state. See DESIGN.md, Entries 31–33.
import { useState } from 'react';
import type { ButtonHTMLAttributes } from 'react';
import './tokens.css';
import './toggle.css';

export type InputSize = 'sm' | 'md' | 'lg';
export type ToggleShape = 'square' | 'pill';

type Props = {
	checked?: boolean;
	defaultChecked?: boolean;
	disabled?: boolean;
	size?: InputSize;
	shape?: ToggleShape;
	/** Optional visible label rendered after the switch. */
	label?: string;
	onCheckedChange?: (checked: boolean) => void;
} & Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type' | 'onChange' | 'onClick'>;

export function Toggle({
	checked,
	defaultChecked = false,
	disabled = false,
	size = 'md',
	shape = 'pill',
	label,
	onCheckedChange,
	...rest
}: Props) {
	const isControlled = checked !== undefined;
	const [internal, setInternal] = useState(defaultChecked);
	const value = isControlled ? checked : internal;

	function toggle() {
		const next = !value;
		if (!isControlled) setInternal(next);
		onCheckedChange?.(next);
	}

	return (
		<button
			{...rest}
			type="button"
			role="switch"
			className="glass-toggle"
			data-size={size}
			data-shape={shape}
			aria-checked={value}
			data-checked={value}
			disabled={disabled}
			onClick={toggle}
		>
			<span className="glass-toggle__track">
				<span className="glass-toggle__thumb" />
			</span>
			{label ? <span className="glass-toggle__label">{label}</span> : null}
		</button>
	);
}

export default Toggle;

// src/lib/glassmorphism/Toggle.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from 'svelte/elements';
	import type { InputSize, ToggleShape } from './options.js';
	import '../styles/glassmorphism.css';
	import './css/toggle.css';

	// A11y: a real <button role="switch"> with aria-checked — keyboard-operable and
	// announced correctly. The on/off STATE is carried by the track colour (frosted
	// vs indigo, a clear ≥3:1 shift) plus thumb position, not by a subtle edge.
	type Props = {
		checked?: boolean;
		disabled?: boolean;
		size?: InputSize;
		shape?: ToggleShape;
		/** Optional visible label rendered after the switch. */
		label?: string;
	} & Omit<HTMLButtonAttributes, 'type'>;

	let {
		checked = $bindable(false),
		disabled = false,
		size = 'md',
		shape = 'pill',
		label,
		...rest
	}: Props = $props();
</script>

<button
	{...rest}
	type="button"
	role="switch"
	class="glass-toggle"
	data-size={size}
	data-shape={shape}
	aria-checked={checked}
	data-checked={checked}
	{disabled}
	onclick={() => (checked = !checked)}
>
	<span class="glass-toggle__track">
		<span class="glass-toggle__thumb"></span>
	</span>
	{#if label}<span class="glass-toggle__label">{label}</span>{/if}
</button>
