// registry/swiss/checkbox/Checkbox.tsx
// Swiss — Checkbox (React skin, Layer 3). A visually-hidden native checkbox drives
// state + a11y; the styled box renders the Swiss look (flat ink fill + white tick).
// The fill is driven by `data-checked` (JS state), so this is controlled-with-
// uncontrolled-fallback: pass `checked` to control it, or leave it and it tracks its
// own state (`defaultChecked` sets the initial value).
import { useState } from 'react';
import type { ChangeEvent, InputHTMLAttributes } from 'react';
import './tokens.css';
import './checkbox.css';

export type InputSize = 'sm' | 'md' | 'lg';
export type CheckboxShape = 'square' | 'pill';

type Props = {
	checked?: boolean;
	defaultChecked?: boolean;
	disabled?: boolean;
	size?: InputSize;
	shape?: CheckboxShape;
	/** Optional visible label rendered after the box. */
	label?: string;
	onChange?: (e: ChangeEvent<HTMLInputElement>) => void;
} & Omit<
	InputHTMLAttributes<HTMLInputElement>,
	'type' | 'size' | 'checked' | 'defaultChecked' | 'onChange'
>;

export function Checkbox({
	checked,
	defaultChecked = false,
	disabled = false,
	size = 'md',
	shape = 'square',
	label,
	onChange,
	...rest
}: Props) {
	const isControlled = checked !== undefined;
	const [internal, setInternal] = useState(defaultChecked);
	const value = isControlled ? checked : internal;

	function handleChange(e: ChangeEvent<HTMLInputElement>) {
		if (!isControlled) setInternal(e.target.checked);
		onChange?.(e);
	}

	return (
		<label
			className="swiss-checkbox"
			data-size={size}
			data-shape={shape}
			data-checked={value}
			data-disabled={disabled}
		>
			<input
				type="checkbox"
				className="swiss-checkbox__input"
				checked={value}
				disabled={disabled}
				onChange={handleChange}
				{...rest}
			/>
			<span className="swiss-checkbox__box">
				<svg
					className="swiss-checkbox__check"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					strokeWidth={3}
					strokeLinecap="round"
					strokeLinejoin="round"
					aria-hidden="true"
				>
					<polyline points="20 6 9 17 4 12" />
				</svg>
			</span>
			{label ? <span className="swiss-checkbox__label">{label}</span> : null}
		</label>
	);
}

export default Checkbox;

// src/lib/swiss/Checkbox.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import type { InputSize, CheckboxShape } from './options.js';
	import '../styles/swiss.css';
	import './css/checkbox.css';

	// Accessible checkbox: a real but visually-hidden native <input type="checkbox">
	// drives state, keyboard, and actual form submission; a styled box beside it
	// renders the Swiss look — a flat ink fill with a white tick when checked.
	// `data-state` is pulled off rest so the docs can force the focus ring on the
	// styled box (the native input is where focus really lands).
	type Props = {
		checked?: boolean;
		disabled?: boolean;
		size?: InputSize;
		shape?: CheckboxShape;
		/** Optional visible label rendered after the box. */
		label?: string;
		// omit native `size` (a number on <input>) — we reuse the name for our scale
	} & Omit<HTMLInputAttributes, 'type' | 'size'>;

	let {
		checked = $bindable(false),
		disabled = false,
		size = 'md',
		shape = 'square',
		label,
		'data-state': dataState,
		...rest
	}: Props = $props();
</script>

<label
	class="swiss-checkbox"
	data-size={size}
	data-shape={shape}
	data-checked={checked}
	data-disabled={disabled}
	data-state={dataState}
>
	<input type="checkbox" class="swiss-checkbox__input" bind:checked {disabled} {...rest} />
	<span class="swiss-checkbox__box">
		<svg
			class="swiss-checkbox__check"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="3"
			stroke-linecap="round"
			stroke-linejoin="round"
			aria-hidden="true"
		>
			<polyline points="20 6 9 17 4 12" />
		</svg>
	</span>
	{#if label}<span class="swiss-checkbox__label">{label}</span>{/if}
</label>
