// src/lib/glassmorphism/Skeleton.svelte
<script lang="ts">
	import type { SkeletonShape } from './options.js';
	import '../styles/glassmorphism.css';
	import './css/skeleton.css';

	// A loading placeholder — decorative, not interactive. `text` renders N lines
	// (last one short); `rect`/`circle` are single blocks. Glass's take on "loading":
	// a frosted translucent surface with a soft highlight that sweeps across (shimmer)
	// — the airy counterpart to NB's blunt opacity pulse.
	type Props = {
		shape?: SkeletonShape;
		/** For `text`: how many lines. */
		lines?: number;
		/** CSS width (e.g. '100%', '20rem'); for `circle` this is the diameter. */
		width?: string;
		/** CSS height — `rect` only. */
		height?: string;
	};
	let { shape = 'text', lines = 5, width, height }: Props = $props();

	const lineWidths = $derived(
		Array.from({ length: Math.max(1, lines) }, (_, i) =>
			i === lines - 1 && lines > 1 ? '60%' : '100%'
		)
	);
</script>

{#if shape === 'text'}
	<div
		class="glass-skeleton glass-skeleton--text"
		role="status"
		aria-label="Loading"
		style:width={width || undefined}
	>
		{#each lineWidths as w, i (i)}
			<span class="glass-skeleton__bar" style:width={w}></span>
		{/each}
	</div>
{:else}
	<span
		class="glass-skeleton glass-skeleton--{shape}"
		role="status"
		aria-label="Loading"
		style:width={width || undefined}
		style:height={shape === 'rect' ? height || undefined : undefined}
	></span>
{/if}

// registry/glassmorphism/skeleton/Skeleton.tsx
// Glassmorphism — Skeleton (React skin, Layer 3). Loading placeholder: `text` renders
// N lines (last one short); `rect`/`circle` are single sized blocks. See DESIGN.md,
// Entries 31–33.
import type { CSSProperties } from 'react';
import './tokens.css';
import './skeleton.css';

export type SkeletonShape = 'text' | 'rect' | 'circle';

type Props = {
	shape?: SkeletonShape;
	/** For `text`: how many lines. */
	lines?: number;
	/** CSS width (e.g. '100%', '20rem'); for `circle` this is the diameter. */
	width?: string;
	/** CSS height — `rect` only. */
	height?: string;
};

export function Skeleton({ shape = 'text', lines = 5, width, height }: Props) {
	if (shape === 'text') {
		const lineWidths = Array.from({ length: Math.max(1, lines) }, (_, i) =>
			i === lines - 1 && lines > 1 ? '60%' : '100%'
		);
		return (
			<div className="glass-skeleton glass-skeleton--text" role="status" aria-label="Loading" style={{ width }}>
				{lineWidths.map((w, i) => (
					<span key={i} className="glass-skeleton__bar" style={{ width: w }} />
				))}
			</div>
		);
	}
	const style: CSSProperties = { width };
	if (shape === 'rect') style.height = height;
	return (
		<span className={`glass-skeleton glass-skeleton--${shape}`} role="status" aria-label="Loading" style={style} />
	);
}

export default Skeleton;
