// src/lib/glassmorphism/Field.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { FieldShape, InputSize } from './options.js';
	import { setFieldContext } from './field-context.js';
	import '../styles/glassmorphism.css';
	import './css/field.css';

	// A form-field wrapper: a label (with optional required mark) above a control
	// (the children), and a help line or an error message below. A <label>, so
	// clicking the label focuses the wrapped control natively — for single text-style
	// controls (Input, Textarea, Select).
	//
	// Field can't reach the control through the snippet, so it PUBLISHES context
	// (invalid + the message id + size) which the control reads to wire its own
	// aria-invalid / aria-describedby and inherit the field size. When `error` is
	// set it replaces the help line, switches the message to the error treatment,
	// and — via that context — flags the control (danger border + aria-invalid).
	type Props = {
		label?: string;
		help?: string;
		error?: string;
		required?: boolean;
		size?: InputSize;
		shape?: FieldShape;
		children?: Snippet;
	};

	let {
		label,
		help,
		error,
		required = false,
		size = 'md',
		shape = 'square',
		children
	}: Props = $props();

	// SSR-stable ids so the wrapped control can point aria-describedby at whichever
	// line is showing, and a screen reader announces the error (role="alert").
	const uid = $props.id();
	const errorId = `${uid}-error`;
	const helpId = `${uid}-help`;
	const describedBy = $derived(error ? errorId : help ? helpId : undefined);

	setFieldContext({
		get invalid() {
			return !!error;
		},
		get describedById() {
			return describedBy;
		},
		get size() {
			return size;
		}
	});
</script>

<label class="glass-field" data-shape={shape} data-size={size}>
	{#if label}
		<span class="glass-field__label">
			{label}{#if required}<span class="glass-field__req"> *</span>{/if}
		</span>
	{/if}
	{@render children?.()}
	{#if error}
		<span id={errorId} class="glass-field__msg glass-field__msg--error" role="alert">{error}</span>
	{:else if help}
		<span id={helpId} class="glass-field__msg">{help}</span>
	{/if}
</label>

// registry/neo-brutalism/field/Field.tsx
// Neo-Brutalism — Field (React skin, Layer 3). A <label> wrapper: label (+ optional
// required mark) above a control (children), help or error line below. Clicking the
// label focuses the wrapped control natively. See DESIGN.md, Entries 31–33.
//
// Field can't reach the control through `children`, so it PROVIDES context
// (invalid + the message id + size); the control reads it to wire its own
// aria-invalid / aria-describedby and inherit the field size (see field-context.ts).
import type { ReactNode } from 'react';
import { useId } from 'react';
import './tokens.css';
import './field.css';
import { FieldContext, type FieldSize } from './field-context';

export type FieldShape = 'square' | 'pill';

type Props = {
	label?: string;
	help?: string;
	error?: string;
	required?: boolean;
	size?: FieldSize;
	shape?: FieldShape;
	children?: ReactNode;
};

export function Field({
	label,
	help,
	error,
	required = false,
	size = 'md',
	shape = 'square',
	children
}: Props) {
	// SSR-stable ids so the wrapped control can point aria-describedby at whichever
	// line is showing, and a screen reader announces the error (role="alert").
	const uid = useId();
	const errorId = `${uid}-error`;
	const helpId = `${uid}-help`;
	const describedById = error ? errorId : help ? helpId : undefined;
	return (
		<label className="nb-field" data-shape={shape} data-size={size}>
			{label ? (
				<span className="nb-field__label">
					{label}
					{required ? <span className="nb-field__req"> *</span> : null}
				</span>
			) : null}
			<FieldContext.Provider value={{ invalid: !!error, describedById, size }}>
				{children}
			</FieldContext.Provider>
			{error ? (
				<span id={errorId} className="nb-field__msg nb-field__msg--error" role="alert">
					{error}
				</span>
			) : help ? (
				<span id={helpId} className="nb-field__msg">
					{help}
				</span>
			) : null}
		</label>
	);
}

export default Field;
