// src/lib/neo-brutalism/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';
	import type { ButtonVariant, ButtonSize, ButtonShape } from './options.js';
	import '../styles/neo-brutalism.css';
	// Layer 2 (the style) is a global stylesheet shared with the aronia registry —
	// plain-CSS imports are unscoped in Svelte, so the same file drives both.
	import './css/button.css';

	// Polymorphic: pass `href` to render an <a>, otherwise a <button>.
	// Rest props are forwarded to whichever element we render.
	type Props = {
		variant?: ButtonVariant;
		size?: ButtonSize;
		shape?: ButtonShape;
		disabled?: boolean;
		href?: string;
		/** Optional leading icon (a snippet, so callers control the markup). */
		icon?: Snippet;
		children?: Snippet;
	} & Omit<HTMLButtonAttributes & HTMLAnchorAttributes, 'href'>;

	let {
		variant = 'primary',
		size = 'md',
		shape = 'square',
		disabled = false,
		href,
		icon,
		children,
		...rest
	}: Props = $props();

	const asLink = $derived(href !== undefined && !disabled);
</script>

<!--
	Data attributes (not dynamic class names) drive the styling so Svelte's
	scoped-CSS analysis keeps every selector — dynamic class strings can be
	pruned as "unused".
-->
{#snippet content()}
	{#if icon}<span class="nb-btn__icon">{@render icon()}</span>{/if}
	{#if children}<span class="nb-btn__label">{@render children()}</span>{/if}
{/snippet}

{#if asLink}
	<a class="nb-btn" data-variant={variant} data-size={size} data-shape={shape} {href} {...rest}>
		{@render content()}
	</a>
{:else}
	<button
		class="nb-btn"
		data-variant={variant}
		data-size={size}
		data-shape={shape}
		{disabled}
		{...rest}
	>
		{@render content()}
	</button>
{/if}

// registry/neo-brutalism/button/Button.tsx
// Neo-Brutalism — Button (React skin, Layer 3)
//
// A thin mapper: props → `data-*` attributes on `.nb-btn`. All the styling
// lives in the co-located CSS (button.css + tokens.css) — this file only wires
// props to attributes, so it reads as the worked example an agent imitates when
// generating new components in the same language. See DESIGN.md, Entries 31–32.
import type { AnchorHTMLAttributes, ButtonHTMLAttributes, ReactNode } from 'react';
import './tokens.css';
import './button.css';

export type ButtonVariant = 'primary' | 'secondary' | 'muted' | 'ghost';
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg';
export type ButtonShape = 'square' | 'pill';

type BaseProps = {
	variant?: ButtonVariant;
	size?: ButtonSize;
	shape?: ButtonShape;
	disabled?: boolean;
	/** Pass an href to render an <a>, otherwise a <button>. */
	href?: string;
	/** Optional leading icon. */
	icon?: ReactNode;
	children?: ReactNode;
};

// Rest props are forwarded to whichever element we render.
type Props = BaseProps &
	Omit<ButtonHTMLAttributes<HTMLButtonElement> & AnchorHTMLAttributes<HTMLAnchorElement>, 'href'>;

export function Button({
	variant = 'primary',
	size = 'md',
	shape = 'square',
	disabled = false,
	href,
	icon,
	children,
	...rest
}: Props) {
	const content = (
		<>
			{icon ? <span className="nb-btn__icon">{icon}</span> : null}
			{children ? <span className="nb-btn__label">{children}</span> : null}
		</>
	);

	// Polymorphic: an href (when not disabled) renders a link, else a button.
	const asLink = href !== undefined && !disabled;

	if (asLink) {
		return (
			<a
				className="nb-btn"
				data-variant={variant}
				data-size={size}
				data-shape={shape}
				href={href}
				{...(rest as AnchorHTMLAttributes<HTMLAnchorElement>)}
			>
				{content}
			</a>
		);
	}

	return (
		<button
			className="nb-btn"
			data-variant={variant}
			data-size={size}
			data-shape={shape}
			disabled={disabled}
			{...(rest as ButtonHTMLAttributes<HTMLButtonElement>)}
		>
			{content}
		</button>
	);
}

export default Button;
